package edu.virginia.cs.androidapp2

import kotlinx.coroutines.flow.Flow

class GameRepository(
    private val gameDao: GameDao,
    private val gameAPI: GameAPIService
) {
    fun getGames(date: Long, gender: String): Flow<List<Game>> {
        return gameDao.getGames(date, gender)
    }

    suspend fun refreshGames(date: Long, gender: String) {
        val month: String = DateTimeUtil.getMonthStringFromMS(date)
        val day: String = DateTimeUtil.getDayStringFromMS(date)
        val year: String = DateTimeUtil.getYearStringFromMS(date)

        try {
            val gamesRemoteData: GamesRemoteData = gameAPI.getGameRemoteData(gender, month, day, year)

            for (gameWrapper in gamesRemoteData.games) {
                // get game off of wrapper
                val gameRemoteData: GameRemoteData = gameWrapper.game

                // Strip fields from raw, deeply nested game objects from api
                val id = gameRemoteData.id.toLong()

                val home = gameRemoteData.home.names.short
                val away = gameRemoteData.away.names.short

                // my IDE generated this (it is good logic, so I kept it)
                val winner: String? = if (gameRemoteData.home.winner) {
                    "home"
                } else if (gameRemoteData.away.winner) {
                    "away"
                } else {
                    null
                }

                // if these are unset ("") because game is in "pre" state, then these will be null
                val homeScore = gameRemoteData.home.score.toIntOrNull()
                val awayScore = gameRemoteData.away.score.toIntOrNull()

                val gameState = gameRemoteData.gameState
                // also generated by IDE
                val period: String? = if (gameState != "pre") {
                    gameRemoteData.currentPeriod
                } else {
                    null
                }

                val contestClock = gameRemoteData.contestClock
                val startTime = gameRemoteData.startTimeEpoch.toLong()

                // create Game database object and insert into room db
                val game = Game(
                    id = id,
                    home = home,
                    away = away,
                    winner = winner,
                    homeScore = homeScore,
                    awayScore = awayScore,
                    gameState = gameState,
                    period = period,
                    contestClock = contestClock,
                    startTime = startTime,
                    date = date,
                    gender = gender
                )

                gameDao.insert(game)
            }
        } catch (e: Exception) {
            // TODO: handle error (I need to stop the loading in the viewmodel when this happens)
        } finally {

        }
    }
}