package edu.virginia.cs.androidapp2

import kotlinx.coroutines.flow.Flow

// Gemini 3 Pro generated this RefreshResult enum for me
sealed interface RefreshResult {
    data object SUCCESS : RefreshResult
    data object ERROR : RefreshResult
}

class GameRepository(
    private val gameDao: GameDao,
    private val gameAPI: GameAPIService
) {
    fun getGames(date: Long, gender: String): Flow<List<Game>> {
        return gameDao.getGames(date, gender)
    }

    suspend fun refreshGames(date: Long, gender: String): RefreshResult {
        val month: String = DateTimeUtil.getMonthStringFromMS(date)
        val day: String = DateTimeUtil.getDayStringFromMS(date)
        val year: String = DateTimeUtil.getYearStringFromMS(date)

        try {
            val gamesRemoteData: GamesRemoteData = gameAPI.getGameRemoteData(gender, month, day, year)

            val gamesList: MutableList<Game> = mutableListOf()

            for (gameWrapper in gamesRemoteData.games) {
                // get game off of wrapper
                val gameRemoteData: GameRemoteData = gameWrapper.game

                // Strip fields from raw, deeply nested game objects from api
                val id = gameRemoteData.id.toLong()

                val home = gameRemoteData.home.names.short
                val away = gameRemoteData.away.names.short

                // my IDE generated this (it is good logic, so I kept it)
                val winner: String? = if (gameRemoteData.home.winner) {
                    "home"
                } else if (gameRemoteData.away.winner) {
                    "away"
                } else {
                    null
                }

                // if these are unset ("") because game is in "pre" state, then these will be null
                val homeScore = gameRemoteData.home.score.toIntOrNull()
                val awayScore = gameRemoteData.away.score.toIntOrNull()

                val gameState = gameRemoteData.gameState
                // also generated by IDE
                val period: String? = if (gameState != "pre") {
                    gameRemoteData.currentPeriod
                } else {
                    null
                }

                val contestClock = gameRemoteData.contestClock
                val startTime: Long? = gameRemoteData.startTimeEpoch.toLongOrNull()  // in case this is ever "", made it nullable

                // create Game database object and insert into room db
                val game = Game(
                    id = id,
                    home = home,
                    away = away,
                    winner = winner,
                    homeScore = homeScore,
                    awayScore = awayScore,
                    gameState = gameState,
                    period = period,
                    contestClock = contestClock,
                    startTime = startTime,
                    date = date,
                    gender = gender
                )

                gamesList.add(game)
            }

            gameDao.insertAll(gamesList.toList())
        } catch (e: Exception) {
            // Gemini 3 Pro suggested this to ensure that I do not mistakenly suppress a coroutine's cancellation
            if (e is kotlinx.coroutines.CancellationException) {
                throw e // Let coroutines handle cancellation
            }

            return RefreshResult.ERROR
        }

        return RefreshResult.SUCCESS
    }
}