package edu.virginia.cs.androidapp2

import kotlinx.coroutines.runBlocking
import org.junit.Test
import java.time.LocalDate
import java.time.ZoneOffset

// Gemini 3 assisted me in writing these tests
class APITest {
    @Test
    fun testFetch() = runBlocking {
        val gender = "men"
        val month = "03"
        val day = "04"
        val year = "2026"

        val date = LocalDate.of(year.toInt(), month.toInt(), day.toInt())
            .atStartOfDay(ZoneOffset.UTC)
            .toInstant()
            .toEpochMilli()

        try {
            val gamesRemoteData: GamesRemoteData = GameAPI.api.getGameRemoteData(gender, month, day, year)

            val gamesList: MutableList<Game> = mutableListOf()

            for (gameWrapper in gamesRemoteData.games) {
                // get game off of wrapper
                val gameRemoteData: GameRemoteData = gameWrapper.game

                // Strip fields from raw, deeply nested game objects from api
                val id = gameRemoteData.id.toLong()

                val home = gameRemoteData.home.names.short
                val away = gameRemoteData.away.names.short

                // my IDE generated this (it is good logic, so I kept it)
                val winner: String? = if (gameRemoteData.home.winner) {
                    "home"
                } else if (gameRemoteData.away.winner) {
                    "away"
                } else {
                    null
                }

                // if these are unset ("") because game is in "pre" state, then these will be null
                val homeScore = gameRemoteData.home.score.toIntOrNull()
                val awayScore = gameRemoteData.away.score.toIntOrNull()

                val gameState = gameRemoteData.gameState
                // also generated by IDE
                val period: String? = if (gameState != "pre") {
                    gameRemoteData.currentPeriod
                } else {
                    null
                }

                val contestClock = gameRemoteData.contestClock
                val startTime: Long? = gameRemoteData.startTimeEpoch.toLongOrNull()  // in case this is ever "", made it nullable

                // create Game database object and insert into room db
                val game = Game(
                    id = id,
                    home = home,
                    away = away,
                    winner = winner,
                    homeScore = homeScore,
                    awayScore = awayScore,
                    gameState = gameState,
                    period = period,
                    contestClock = contestClock,
                    startTime = startTime,
                    date = date,
                    gender = gender
                )

                gamesList.add(game)
            }

            print(gamesList)
        } catch (e: Exception) {
            print(e.message)
            e.printStackTrace()
        }
    }
}